### ISSUE TITLE
Falta ztreamyPublisher-0.4.2.dev13.jar

### ISSUE THREAD

**Issue by jfisteus** [hermes-smartcity/hermes-simulator#3]
He intentado probar tu versión más reciente del simulador, pero no la puedo compilar porque me falta el fichero `my-repo/ztreamy/ztreamyPublisher/0.4.2.dev13/ztreamyPublisher-0.4.2.dev13.jar`

He intentado poner yo el fichero desde el repositorio de Ztreamy, pero el proyecto no compila porque parece que has añadido algún cambio a `ztreamyPublisher` que yo no tengo (como mínimo, el método `Event.getTimestamp()`)

De paso, si lo ves conveniente me puedes poner un pull-request con tu nueva versión de `ztreamyPublisher` en el repositorio de Ztreamy, o simplemente pasarme el código y la añado yo.

**Comment by jorgeyago** [comment]
Efectivamente, los JARs están excluidos de forma inherente al subir el código y se me pasó subirlo manualmente.
El cambio del 'Publisher' es el que comentamos en la audioconferencia del 20/09 para poder acceder al 'Timestamp' que le asignabas al 'Event'.
He hecho el 'commit' del JAR y ya debería estar disponible.
